import React from 'react'

const Trap = () => {
  return (
   <div className="casino-table"><div className="casino-table-box"><div className="casino-table-left-box"><div className="casino-table-body"><div className="casino-table-row "><div className="casino-nation-detail"><div className="casino-nation-name">Player A</div><div className="casino-nation-book text-success"></div></div><div className="casino-odds-box back"><span className="casino-odds">1.72</span></div><div className="casino-odds-box lay"><span className="casino-odds">1.77</span></div></div></div></div><div className="casino-table-box-divider"></div><div className="casino-table-right-box"><div className="casino-table-body"><div className="casino-table-row "><div className="casino-nation-detail"><div className="casino-nation-name">Player B</div><div className="casino-nation-book text-success"></div></div><div className="casino-odds-box back suspended-box"><span className="casino-odds">0</span></div><div className="casino-odds-box lay suspended-box"><span className="casino-odds">0</span></div></div></div></div></div><div className="casino-table-box mt-3 sevenupbox"><div className="casino-table-left-box"><h4 className="d-md-none mb-2">Player</h4><div className="seven-up-down-box"><div className="up-box"><div className="up-down-book"></div><div className="text-end"><div className="up-down-odds">2.04</div><span>Low</span></div></div><div className="down-box"><div className="up-down-book"></div><div className="text-start"><div className="up-down-odds">1.95</div><span>High</span></div></div><div className="seven-box"><img src="https://versionobj.ecoassetsservice.com/v36/static/front/img/trape-seven.png"/></div></div></div><div className="casino-table-box-divider"></div><div className="casino-table-right-box"><div className="casino-table-body"><div className="casino-table-row "><div className="casino-nation-detail"><div className="casino-nation-name"><img src="https://versionobj.ecoassetsservice.com/v36/static/front/img/cards/J.png"/><img src="https://versionobj.ecoassetsservice.com/v36/static/front/img/cards/Q.png"/><img src="https://versionobj.ecoassetsservice.com/v36/static/front/img/cards/K.png"/></div><div className="casino-nation-book "></div></div><div className="casino-odds-box back"><span className="casino-odds">4.09</span></div><div className="casino-odds-box lay"><span className="casino-odds">4.41</span></div></div></div></div></div><div className="casino-remark mt-3">
    {/* <marquee scrollamount="3">IT'S EITHER PLAYER A OR B, WHO SCORES A TOTAL OF 13,14,15 WILL FALL INTO THE TRAP &amp; LOSE THE GAME. AVOID FALLING INTO THE TRAP &amp; WIN REAL MONEY.</marquee> */}
    </div></div>
  )
}

export default Trap